### ISSUE TITLE
Dungeons not generating

### ISSUE THREAD

**Issue by srnyx** [Draylar/deep-dungeons#5]
When I do /locate deepdungeons:standard_dungeon, it says it can't find this structure.

**Comment by K0-RR** [comment]
It does
![image](https://user-images.githubusercontent.com/43277609/111086194-2669a100-851b-11eb-8ac1-af9c32c9f2b5.png)
Probably some incompatibility with your mods.

**Comment by srnyx** [comment]
> It does
> ![image](https://user-images.githubusercontent.com/43277609/111086194-2669a100-851b-11eb-8ac1-af9c32c9f2b5.png)
> Probably some incompatibility with your mods.

Is standard_dungeon the only one that's supposed to show up?
I'm using Carpet, does that cause anything conflictions?

**Comment by srnyx** [comment]
Bump

**Comment by K0-RR** [comment]
Bumping like this is just rude. You know you need to do some work on your side right? Nobody can’t help you if you don’t put minimum effort it this like providing your mod list. It doesn’t work only for you so try to locate the source of the problem by starting the game with only DD and then adding another mod, checking if the command works. If it does then add next one etc.

**Comment by srnyx** [comment]
> Bumping like this is just rude. You know you need to do some work on your side right? Nobody can’t help you if you don’t put minimum effort it this like providing your mod list. It doesn’t work only for you so try to locate the source of the problem by starting the game with only DD and then adding another mod, checking if the command works. If it does then add next one etc.

I was just asking if **standard_dungeon** was the only one that was supposed to show up (why go through all of the trouble to check if you could easily answer the question [I replied only 30 minutes after to you saying "it does"]) and if Carpet causes any conflicts...
If I don't get a reply within a few days then I assume the author (or person I was replying to) forgot about my issue or something similar.
And how would I know what you need? Providing information that isn't needed can be misleading and cause confusion.

**Comment by srnyx** [comment]
wait ur not even author im so dumb

**Comment by srnyx** [comment]
Client mods: https://imgur.com/a/lGA97oK
Server mods: https://imgur.com/a/1rCPvsl

**Comment by srnyx** [comment]
https://github.com/TheGrimsey/Stoneholm/issues/1#issuecomment-810352988
